config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'weather#new'
  resources :weather, only: [:new, :create]
  get 'weather/show/:zip', to: 'weather#show', as: 'show_weather'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  def new
    # no-op
  end

  def create
    weather_data = fetch_weather(params[:street_address], params[:city], params[:state], params[:zip])
  
    if weather_data['cod'] != 200
      flash[:error] = "Error: #{weather_data['message']}"
      redirect_to root_path
    else
      @cached = weather_data['cached']
      
      redirect_to show_weather_path(zip: params[:zip], cached: @cached)
    end
  rescue StandardError => e
    flash[:error] = "Error: #{e.message}"
    redirect_to root_path
  end

  def show
    zip = params[:zip]
    @cached = params[:cached] == 'true'

    weather_data = Rails.cache.fetch(zip)

    if weather_data
      @temperature = weather_data['main']['temp']
      @low = weather_data['main']['temp_min']
      @high = weather_data['main']['temp_max']
      @sunrise = Time.at(weather_data['sys']['sunrise'])
      @sunset = Time.at(weather_data['sys']['sunset'])
    else
      flash[:error] = 'No cached weather data available for this zip code.'
      redirect_to root_path
    end
  end  

  private

  def fetch_weather(street_address, city, state, zip)
    weather_client = OpenWeatherMap.new
    weather_data = weather_client.get_weather(street_address, city, state, zip)
    weather_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppleTakeHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>  </body>
</html>

app/views/weather/new.html.erb
<div class="container h-100 d-flex justify-content-center align-items-center">
  <div class="col-4">
    <h1 class="text-center mb-4">Enter Your Address</h1>

    <%= form_with url: weather_index_path, method: :post, local: true do |form| %>
      <div class="form-group mb-3">
        <%= label_tag :street_address, "Street Address" %>
        <%= text_field_tag :street_address, nil, class: "form-control", placeholder: "123 Main St", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= label_tag :city, "City" %>
        <%= text_field_tag :city, nil, class: "form-control", placeholder: "Anytown", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= label_tag :state, "State" %>
        <%= text_field_tag :state, nil, class: "form-control", placeholder: "State", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= label_tag :zip, "Zip" %>
        <%= text_field_tag :zip, nil, class: "form-control", placeholder: "12345", required: true %>
      </div>

      <%= submit_tag "Get Weather", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/weather/show.html.erb
<div class="d-flex justify-content-center align-items-center vh-100">
  <div class="card text-center shadow custom-border-radius bg-white p-5">
    <div class="card-body">
      <h1 class="card-title">Weather Report</h1>

      <% if Time.now >= @sunrise && Time.now <= @sunset %>
        <p>☀️ Daytime</p>
      <% else %>
        <p>🌙 Nighttime</p>
      <% end %>

      <h2 class="card-text">Temperature: <%= @temperature %>°C</h2>
      <h2 class="card-text">Low: <%= @low %>°C</h2>
      <h2 class="card-text">High: <%= @high %>°C</h2>
      <p class="text-center"><%= @cached ? 'This result was fetched from cache.' : 'This result was freshly fetched.' %></p>

      <%= link_to 'Try a different address', new_weather_path, class: 'btn btn-primary mt-4' %>
    </div>
  </div>
</div>